init(core): init books app container
SShlykov/zeitment pull request #1
Opened 2024-02-18 19:26 UTC by vbuglov

2024-02-18 22:05 UTC, SShlykov requested changes
Зачем-то сырое в PR отправил

2024-02-18 22:05 UTC, SShlykov commented on books-ui/src/helpers/adapter/adapter.js
> +    delete mutationObject[oldKey]
mutationObject[newKey] пытается получить доступ к mutationObject[oldKey] после его переименования, но переименование происходит в той же итерации и влияет на оригинальный объект напрямую. Да и кейс, если oldKey не существует в исходном targetObject

2024-02-18 22:05 UTC, SShlykov commented on books-ui/tailwind.config.js
> +
Линтер бы

2024-02-18 22:05 UTC, SShlykov commented on books-ui/vite.config.js
> +// });
Не понятный фрагмент

2024-02-19 07:43 UTC, closed without merging

2024-02-25 08:00 UTC, vabuglov commented on books-ui/src/helpers/adapter/adapter.js
> +    delete mutationObject[oldKey]
Он не влияет на оригинальный объект, так как была создана копия объекта

  const targetObject = {..._targetObject}

2024-02-25 08:04 UTC, vabuglov commented on books-ui/README.md
> +This template should help get you started developing with Vue 3 in Vite. The template uses Vue 3 `<script setup>` SFCs, check out the [script setup docs](https://v3.vuejs.org/api/sfc-script-setup.htm
Эта документация автогенерируется при создания нового проекта, что ты подразумеваешь под базовой документацией?

2024-02-25 08:05 UTC, vabuglov commented on books-ui/tailwind.config.js
> +
Линтер в проекте есть .eslintrc.cjs

2024-02-25 08:06 UTC, vabuglov commented on books-ui/src/helpers/adapter/adapter.js
> +    delete mutationObject[oldKey]
Возможно стоит дать переменной имя copyObject